//
//  File.swift
//  PizzaMenu
//
//  Created by Vetal on 18.08.2022.
//

class DataManager {
    static let dataManager = DataManager()
    
    private init() {}
    
    
    let dishes: [Dish] = [
        Dish(typeDish: .pizza,
             name: "Мангеттен",
             price: 215,
             photo: "Мангеттен",
             description: "Гриби(подвійна порція), Моцарела, Пепероні, Соус Альфредо"),
        Dish(typeDish: .pizza,
             name: "Маргарита",
             price: 215,
             photo: "Маргарита",
             description: "(Подвійна порція моцарели), Моцарела, Соус Domino's"),
        Dish(typeDish: .pizza,
             name: "Барбекю",
             price: 215,
             photo: "Барбекю",
             description: "Курка, Цибуля, Бекон, Гриби, Моцарела, Соус Барбекю"),
        Dish(typeDish: .pizza,
             name: "Папероні з томатами",
             price: 215,
             photo: "Папероні з томатами",
             description: "Моцарела, Пепероні, Помідори, Соус Барбекю"),
        Dish(typeDish: .pizza,
             name: "Техас",
             price: 215,
             photo: "Техас",
             description: "Кукурудза, Цибуля, Гриби, Ковбаски баварські, Моцарела, Соус Барбекю"),
        Dish(typeDish: .pizza,
             name: "Гриль мікс",
             price: 250,
             photo: "Гриль мікс",
             description: "Курка, Фрикадельки, Цибуля, Бекон, Болгарський перець, Моцарела, Соус Барбекю"),
        Dish(typeDish: .pizza,
             name: "Кантрі",
             price: 270,
             photo: "Кантрі",
             description: "Цибуля, Бекон, Шинка, Гриби, Моцарела, Огірки мариновані, Соус Часниковий"),
        
        Dish(typeDish: .saydi,
             name: "Комбо-бокс",
             price: 129,
             photo: "Комбо-бокс",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Комбо-бокс фрі",
             price: 129,
             photo: "Комбо-бокс",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Великий бокс картоплі",
             price: 129,
             photo: "Великий бокс картоплі",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Хлібці з мюнхенськими ковбасками",
             price: 129,
             photo: "Хлібці з мюнхенськими ковбасками",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Хлібці з баварськими ковбасками та томатами",
             price: 126,
             photo: "Хлібці з баварськими ковбасками та томатами",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Хлібці з шпенатом і фетою",
             price: 125,
             photo: "Хлібці з шпенатом і фетою",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Хлібці з беконом і халапеньо",
             price: 126,
             photo: "Хлібці з беконом і халапеньо",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Курячі крильця",
             price: 165,
             photo: "Курячі крильця",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Курячі стріпси",
             price: 159,
             photo: "Курячі стріпси",
             description: ""),
        Dish(typeDish: .saydi,
             name: "Картопля фрі з печі",
             price: 60,
             photo: "Картопля фрі з печі",
             description: ""),
        Dish(typeDish: .desert,
             name: "Абрикосові роли",
             price: 110,
             photo: "Абрикосові роли",
             description: ""),
        Dish(typeDish: .desert,
             name: "Шоколадні роли",
             price: 105,
             photo: "Шоколадні роли",
             description: ""),
        Dish(typeDish: .desert,
             name: "Вишневі роли",
             price: 110,
             photo: "Вишневі роли",
             description: ""),
        Dish(typeDish: .desert,
             name: "Крем-сир роли",
             price: 110,
             photo: "Крем-сир роли",
             description: ""),
        Dish(typeDish: .desert,
             name: "Лате мафін з маршмелоу",
             price: 60,
             photo: "Лате мафін з маршмелоу",
             description: ""),
        Dish(typeDish: .desert,
             name: "Лава кейк",
             price: 86,
             photo: "Лава кейк",
             description: ""),
        Dish(typeDish: .desert,
             name: "Мафін кокосовий",
             price: 86,
             photo: "Мафін кокосовий",
             description: ""),
        Dish(typeDish: .drink,
             name: "Вода негазована 1л.",
             price: 31,
             photo: "Вода негазована 1л.",
             description: ""),
        Dish(typeDish: .drink,
             name: "Coca-Cola 1л.",
             price: 57,
             photo: "Coca-Cola 1л.",
             description: ""),
        Dish(typeDish: .drink,
             name: "Fuze-Tea зі смаком лимону 1л.",
             price: 60,
             photo: "Fuze-Tea зі смаком лимону 1л.",
             description: ""),
        Dish(typeDish: .drink,
             name: "Rich Апельсин",
             price: 58,
             photo: "Rich Апельсин",
             description: ""),
        Dish(typeDish: .drink,
             name: "Rich Банан-Полуниця 1л.",
             price: 58,
             photo: "Rich Банан-Полуниця 1л.",
             description: ""),
        Dish(typeDish: .drink,
             name: "Rich Томат",
             price: 58,
             photo: "Rich Томат",
             description: ""),
        
        
        
    ]
    
}
